In [3]:
import numpy as np

my_list = [1, 2, 3, 4]
my_array = np.array([1, 2, 3, 4])

print(my_list * 2)     # [1, 2, 3, 4, 1, 2, 3, 4]  — lists just repeat themselves
print(my_array * 2)   

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [4]:
a = np.array([1, 2, 3])
zeros = np.zeros(5)              # [0. 0. 0. 0. 0.]
ones = np.ones((2, 3))           # a 2-row, 3-column grid of 1s
sequence = np.arange(0, 10, 2)   # [0 2 4 6 8] — like range(), but returns an array directly

print(a, zeros, ones, sequence, sep="\n")

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


In [5]:
prices = np.array([10, 20, 30, 40])
discounted = prices * 0.9        # 10% off everything, no loop
print(discounted)                 # [ 9. 18. 27. 36.]

is_expensive = prices > 25
print(is_expensive)               # [False False  True  True]  — comparison on every element at once

print(prices[is_expensive])       # [30 40]  — use that True/False array to filter!

[ 9. 18. 27. 36.]
[False False  True  True]
[30 40]


In [6]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid.shape)     # (2, 3) — 2 rows, 3 columns
print(grid[0])         # [1 2 3] — first row
print(grid[:, 1])      # [2 5]    — second column, every row

(2, 3)
[1 2 3]
[2 5]


In [23]:
arr = np.arange(25).reshape(5, 5)  # 5x5 grid of numbers from 0 to 24
print(arr)
arr = arr[::3, 0:3]  # slice the first 3 rows and first 3 columns
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2]
 [15 16 17]]


In [26]:
arr = np.random.randint(0, 100, (5,5))
print(arr)

evens = arr[arr % 2 == 0]      # boolean mask → 1D array of even values
print(evens)
arr[:, -1] = 0 
print(arr)

[[52 33 64 48 26]
 [17 36 56  8 33]
 [38 75 34 81 85]
 [74 60 69 94 24]
 [46 55 38 96 62]]
[52 64 48 26 36 56  8 38 34 74 60 94 24 46 38 96 62]
[[52 33 64 48  0]
 [17 36 56  8  0]
 [38 75 34 81  0]
 [74 60 69 94  0]
 [46 55 38 96  0]]


In [28]:
arr = [C * 9/5 + 32 for C in np.array([0, 10, 20, 30, 40])]
print(arr)

[np.float64(32.0), np.float64(50.0), np.float64(68.0), np.float64(86.0), np.float64(104.0)]
